### ISSUE TITLE
VLC doesnt open, console just outputs errors without scrolling all the way down.

### ISSUE THREAD

**Issue by Ozzy4201** [kaboussi/stream-cli#29]
Before inputting choice 
![image](https://user-images.githubusercontent.com/94714886/167271197-58db6685-6a73-4506-9e12-f9f2126012ef.png)

After inputting choice
![image](https://user-images.githubusercontent.com/94714886/167271201-0cce0653-30a0-45bc-9506-15c83f73f5f7.png)

**Comment by Ozzy4201** [comment]
Errors: Traceback (most recent call last):
  File "C:\Users\Ozzy\stream-cli\main.py", line 56, in <module>
    app()al         21.3.0
  File "C:\Users\Ozzy\stream-cli\stream-cli\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Ozzy\stream-cli\stream-cli\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Ozzy\stream-cli\stream-cli\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Ozzy\stream-cli\stream-cli\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ozzy\stream-cli\stream-cli\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Ozzy\stream-cli\stream-cli\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Ozzy\stream-cli\stream-cli\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Ozzy\stream-cli\main.py", line 19, in top
    apprun(TopMoviesSpider, True)
  File "C:\Users\Ozzy\stream-cli\src\runner.py", line 50, in apprun
    stream(magnet, default_player=player)
  File "C:\Users\Ozzy\stream-cli\src\stream.py", line 36, in stream
    subprocess.run(["webtorrent", magnet, f"--{default_player}"], check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run.1.2
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Yes this is with the VENV now btw

**Comment by redelka00** [comment]
Please check these options and run the app after each one:
1. `git pull`
2. try windows [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) to get Linux features inside windows 
3. check if you can run VLC from your terminal by typing `vlc`

**Comment by Ozzy4201** [comment]
Sorry for the late reply, doing git pull seems to have fixed it, sorta. VLC works, WSL makes no difference.

Yields this result instead.

Enter Your Choice (or 0 if you want to quit): 4
Traceback (most recent call last):
  File "C:\Users\Ozzy\stream-cli\main.py", line 56, in <module>
    app()
  File "C:\Users\Ozzy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Ozzy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Ozzy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Ozzy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ozzy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Ozzy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Ozzy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Ozzy\stream-cli\main.py", line 19, in top
    apprun(TopMoviesSpider, True)
  File "C:\Users\Ozzy\stream-cli\src\runner.py", line 54, in apprun
    stream(magnet, default_player=player)
  File "C:\Users\Ozzy\stream-cli\src\stream.py", line 42, in stream
    subprocess.run(["webtorrent", magnet, f"--{default_player}"], check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kaboussi** [comment]
i did manage to solve the problem and it works for me on windows, i have only one issue, how to run VLC.exe anywhere from terminal not only when i'm on the right path, if we can manage to solve this it will work on Windows! 
![Screenshot from 2022-05-17 00-40-06](https://user-images.githubusercontent.com/95357302/168699394-e970aeab-24da-40e0-8a31-cf9a119b8b20.png)

**Comment by kaboussi** [comment]
I did manage to figure it out!
you should add the vlc source folder to your environment variable PATH
update the app by running `git pull`
Feedback Needed!

**Comment by Ozzy4201** [comment]
Well i accidentally closed it, but it seems to work now either way. Tried it now, movie played w/out any issues.

**Comment by kaboussi** [comment]
I'm glad that it works for you, Enjoy :)
