### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by doonayy** [kaboussi/stream-cli#41]
getting this problem running python3 main.py and selecting top

```
Traceback (most recent call last):
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f57355079a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.torrentgalaxy.to', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57355079a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elon/stream-cli/main.py", line 130, in <module>
    main()
  File "/home/elon/stream-cli/main.py", line 87, in main
    get_top(hosts)
  File "/home/elon/stream-cli/main.py", line 14, in get_top
    1: apprun(torrent_galaxy()),
  File "/home/elon/stream-cli/stream_cli/runner.py", line 51, in apprun
    movies = start_scrawling(scraping_class)
  File "/home/elon/stream-cli/stream_cli/runner.py", line 35, in start_scrawling
    response = requests.get("https://www.torrentgalaxy.to/").status_code
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/elon/stream-cli/venv/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.torrentgalaxy.to', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57355079a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

using npm 8.15.1; node 18.7.0 and webtorrent 4.1.0 (1.8.26).

love the project concept, thanks in advance

**Comment by ashroyxi** [comment]
can you view this website from a browser? https://torrentgalaxy.to/
this project uses this website.

**Comment by doonayy** [comment]
sadly not this might be why

**Comment by ashroyxi** [comment]
you can try a vpn or proxy network. i was trying this evening how to implement proxy internally and i didn't succeed. maybe someone else will do it?

**Comment by ashroyxi** [comment]
@kaboussi 
you might recheck leet.py file. i hope this is the file to work with 1337x but i made some changes drastically and seems like it has no effect at all.

**Comment by kaboussi** [comment]
> @kaboussi you might recheck leet.py file. i hope this is the file to work with 1337x but i made some changes drastically and seems like it has no effect at all.

what changes, can you share them?

**Comment by ashroyxi** [comment]
i changed the urls for categories, some choices etc.

**Comment by kaboussi** [comment]
> i changed the urls for categories, some choices etc.

Cool, if you noticed that something needs to be improved or some changes feel free to open a PR or an issue.
Thanks in advance.
